name: flutter_boilerplate
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  pedantic_mono: any
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  mockito: any
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  image_path: "icon/icon.png"
  android: true
  ios: true
  adaptive_icon_foreground: "icon/adaptive_icon.png"
  adaptive_icon_background: "#E4572E"

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
